# Generated by Django 5.2 on 2026-09-27 19:10

import equbApp.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_passwordresetcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=equbApp.uploads.profile_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=equbApp.uploads.profile_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="equbadmin",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=equbApp.uploads.profile_upload_path
            ),
        ),
    ]
