
POST http://49.13.235.107:3006/signup
Content-Type: application/json

{
    "name": "mengistu Mamo",
    "email": "ya@gmail.com",
    "phone": "+251969489521",
    "password": "12345678",
    "re_password": "12345678",
    "referred_by": "",
    "role": "customer"
}


###
POST http://49.13.235.107:3006/signup
Content-Type: application/json

{
    "name": "rock Man",
    "email": "admin10@gmail.com",
    "phone": "+251969489521",
    "password": "12345678",
    "re_password": "12345678",
    "role": "admin"
 }

###
POST http://49.13.235.107:3006/login
Content-Type: application/json

{
    "email": "admin7@gmail.com",
    "password": "12345678"
}


###
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "email": "admin7@gmail.com",
    "password": "12345678"
}

###
POST http://127.0.0.1:8000/admin_equb_types/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json

{
  "name": "weekly"
}


###
GET http://127.0.0.1:8000/admin_equb_types/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json

# Admin  or View, update,create and delete all course
###
POST http://127.0.0.1:8000/admin_equb_categories/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json

{
      "name": "Savings",
      "image": null,
      "description": "This category deals with collective savings."
}

###
GET http://127.0.0.1:8000/admin_equb_categories/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json

###
GET http://127.0.0.1:8000/courses/c3ef554f-d679-4a07-9382-e1adbea5d395/
Authorization: Token d31c1b4046d9afba30ffa4bcb06f607a06d0d5a8
Content-Type: application/json

###
POST http://127.0.0.1:8000/admin_equb_subcategories/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json

{
      "category": "95806bd9-92d4-4988-a781-8c95891fc1a1",
      "name": "Emergency Fund",
      "image": null,
      "description": "A subcategory for saving emergency funds.",
      "default_equb_type": "4483dfb0-94fe-46b7-ba36-c7766d21b9a9"
}
###
GET http://127.0.0.1:8000/admin_equb_subcategories/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json

# Topic Admin or View, update,create and delete all

###
POST http://127.0.0.1:8000/admin_equbs/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json

{
      "name": "Savings Group",
      "owner": "38c0f653-2c77-4345-9313-c7343ccebe3e",
      "subcategory": "0613f056-8991-48d2-b261-7820721d0ecc",
      "start_date": "2024-01-01",
      "end_date": "2025-12-31",
      "lottery_draw_schedule": "2024-12-31",
      "rules_and_conditions": "Members contribute a fixed amount monthly.",
      "rules_and_condit_status": true,
      "payout_system": "first_come_first_serve",
      "total_number_of_members": 10,
      "payment_at_each_round": 1000,
      "created_at": "2024-04-01T10:00:00"
}

###
GET http://127.0.0.1:8000/admin_equbs/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json

###
GET http://127.0.0.1:8000/equbs_by_subcategory/95806bd9-92d4-4988-a781-8c95891fc1a1/
# Authorization: Token d31c1b4046d9afba30ffa4bcb06f607a06d0d5a8
Content-Type: application/json

# subcategories_with_equbs_by_category

###
GET http://127.0.0.1:8000/subcategories_with_equbs_by_category/95806bd9-92d4-4988-a781-8c95891fc1a1/
# Authorization: Token d31c1b4046d9afba30ffa4bcb06f607a06d0d5a8
Content-Type: application/json





# Customer 

# 22e4d1a440894d751fe30ef5770478996cec3a7c

# join_equb

###
POST http://127.0.0.1:8000/join_equb/
Authorization: Token 326323294ec879e27e35ed6d28387ff815eaff2f
Content-Type: application/json


{
      "user": "5",
      "equb": "3bd387b0-cf27-4aa5-ab01-74c0b079747b",
      "status": "active",
      "joined_at": "2024-04-01T10:00:00",
      "payment_status": "paid"
}


# unjoin_equb

###
POST http://127.0.0.1:8000/unjoin_equb/
Authorization: Token 326323294ec879e27e35ed6d28387ff815eaff2f
Content-Type: application/json


{
      "user": "1",
      "equb": "9c2d3c32-2181-44a0-96c6-340389b5ac46"
}

# equb_members

###
GET http://127.0.0.1:8000/all_equb_members/9c2d3c32-2181-44a0-96c6-340389b5ac46/
Authorization: Token 326323294ec879e27e35ed6d28387ff815eaff2f
Content-Type: application/json


# preview_equb_winner

###
GET http://127.0.0.1:8000/preview_equb_winner/3bd387b0-cf27-4aa5-ab01-74c0b079747b/
Authorization: Token 65b84f13f6a49d9cd55b0c28a61a85fd198b9b90
Content-Type: application/json


# confirm_and_save_winner

###
POST http://127.0.0.1:8000/confirm_and_save_winner/
Authorization: Token afb323d5515cf619ae4c1b01dbdc9401cc3aa3da
Content-Type: application/json


{
      "user": "5",
      "equb": "3bd387b0-cf27-4aa5-ab01-74c0b079747b"
}

# "admin_equb_report"

###
GET http://127.0.0.1:8000/admin_equb_report/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json


# equb_detailed_report

###
GET http://127.0.0.1:8000/equb_detailed_report/9c2d3c32-2181-44a0-96c6-340389b5ac46/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json


# list_user_payment_history

###
GET http://127.0.0.1:8000/list_user_payment_history/1/
Authorization: Token 326323294ec879e27e35ed6d28387ff815eaff2f
Content-Type: application/json

###
GET http://127.0.0.1:8000/equbs_users_total_paid/9c2d3c32-2181-44a0-96c6-340389b5ac46/1/
Content-Type: application/json



# users_equb_contributions

###
GET http://127.0.0.1:8000/users_equb_contributions/1/
Content-Type: application/json


###
POST http://127.0.0.1:8000/admin_faqs/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json

{
    "question": "What is Equb?",
    "answer": "Equb is a traditional savings and loan system where members contribute a fixed amount of money regularly and take turns in receiving the collected sum.",
    "is_active": true,
    "created_at": "2025-04-14T10:00:00Z",
    "updated_at": "2025-04-14T10:00:00Z"
  }