
POST http://127.0.0.1:8000/signup
Content-Type: application/json

{
    "name": "Cool Man",
    "email": "abe@gmail.com",
    "phone": "+251969489521",
    "password": "12345678",
    "re_password": "12345678",
    "referred_by": "",
    "role": "customer"
 }

###
POST http://127.0.0.1:8000/signup
Content-Type: application/json

{
    "name": "rock Man",
    "email": "admin@gmail.com",
    "phone": "+251969489521",
    "password": "12345678",
    "re_password": "12345678",
    "role": "admin"
 }

###
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "12345678"
}



###
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "email": "abe@gmail.com",
    "password": "12345678"
}

###
POST http://127.0.0.1:8000/admin_equb_types/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json

{
  "name": "Daily"
}


###
GET http://127.0.0.1:8000/admin_equb_types/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json

# Admin  or View, update,create and delete all course
###
POST http://127.0.0.1:8000/admin_equb_categories/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json

{
      "name": "Savings",
      "image": null,
      "description": "This category deals with collective savings."
}

###
GET http://127.0.0.1:8000/admin_equb_categories/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json
###
GET http://127.0.0.1:8000/courses/c3ef554f-d679-4a07-9382-e1adbea5d395/
Authorization: Token d31c1b4046d9afba30ffa4bcb06f607a06d0d5a8
Content-Type: application/json

###
POST http://127.0.0.1:8000/admin_equb_subcategories/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json

{
      "category": "95806bd9-92d4-4988-a781-8c95891fc1a1",
      "name": "Emergency Fund",
      "image": null,
      "description": "A subcategory for saving emergency funds.",
      "default_equb_type": "146c9ca2-9f62-4828-bba1-660f598a2755"
}
###
GET http://127.0.0.1:8000/admin_equb_subcategories/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json

# Topic Admin or View, update,create and delete all

###
POST http://127.0.0.1:8000/admin_equbs/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json

{
      "name": "Savings Group",
      "owner": "38c0f653-2c77-4345-9313-c7343ccebe3e",
      "subcategory": "e9f393ed-9805-4a46-a90a-6a9a016a3dd6",
      "start_date": "2024-01-01",
      "end_date": "2024-12-31",
      "lottery_draw_schedule": "Every last Saturday of the month",
      "rules_and_conditions": "Members contribute a fixed amount monthly.",
      "rules_and_condit_status": true,
      "payout_system": "first_come_first_serve",
      "total_number_of_members": 10,
      "payment_at_each_round": 1000,
      "created_at": "2024-04-01T10:00:00"
}

###
GET http://127.0.0.1:8000/admin_equbs/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json
###
GET http://127.0.0.1:8000/equbs_by_subcategory/95806bd9-92d4-4988-a781-8c95891fc1a1/
# Authorization: Token d31c1b4046d9afba30ffa4bcb06f607a06d0d5a8
Content-Type: application/json

# subcategories_with_equbs_by_category

###
GET http://127.0.0.1:8000/subcategories_with_equbs_by_category/95806bd9-92d4-4988-a781-8c95891fc1a1/
# Authorization: Token d31c1b4046d9afba30ffa4bcb06f607a06d0d5a8
Content-Type: application/json


###
PUT http://127.0.0.1:8000/topics/877b7fb8-f116-49ca-925c-0aba7fa97316/
Authorization: Token d31c1b4046d9afba30ffa4bcb06f607a06d0d5a8
Content-Type: application/json
{
  "title": "mengsitu Q",
  "course": "c3ef554f-d679-4a07-9382-e1adbea5d395",
  "status": false,
  "createdAt": "2023-01-13 23:17:05",
  "updatedAt": "2023-01-29 07:31:32"
}
###
DELETE http://127.0.0.1:8000/topics/74065b38-f640-41f3-8e17-2bada60e251c/
Authorization: Token d31c1b4046d9afba30ffa4bcb06f607a06d0d5a8
Content-Type: application/json


###
GET http://127.0.0.1:8000/content/
Authorization: Token d31c1b4046d9afba30ffa4bcb06f607a06d0d5a8
Content-Type: application/json
###
GET http://127.0.0.1:8000/content/c8f9d177-80e9-4139-8e01-b598bcd7f15c/
Authorization: Token d31c1b4046d9afba30ffa4bcb06f607a06d0d5a8
Content-Type: application/json

###
PUT http://127.0.0.1:8000/content/f875bd56-9cf2-490e-b000-c740ad3d77b6/
Authorization: Token d31c1b4046d9afba30ffa4bcb06f607a06d0d5a8
Content-Type: application/json

{
  "title": "ababaab",
  "body":"nsjkasnjsan acajb",
  "video":null,
  "topic":"1abc8f7b-c4b9-4bc6-adb9-089e5a1d517b",
  "status": true,
  "created_at": "2023-01-13 23:17:05",
  "updated_at": "2023-01-29 07:31:32"
}
###
DELETE http://127.0.0.1:8000/content/c8f9d177-80e9-4139-8e01-b598bcd7f15c/
Authorization: Token d31c1b4046d9afba30ffa4bcb06f607a06d0d5a8
Content-Type: application/json



# Customer 

# 22e4d1a440894d751fe30ef5770478996cec3a7c

# join_equb

###
POST http://127.0.0.1:8000/join_equb/
Authorization: Token 326323294ec879e27e35ed6d28387ff815eaff2f
Content-Type: application/json


{
      "user": "1",
      "equb": "9c2d3c32-2181-44a0-96c6-340389b5ac46",
      "status": "active",
      "joined_at": "2024-04-01T10:00:00",
      "payment_status": "paid"
}


# unjoin_equb

###
POST http://127.0.0.1:8000/unjoin_equb/
Authorization: Token 326323294ec879e27e35ed6d28387ff815eaff2f
Content-Type: application/json


{
      "user": "1",
      "equb": "9c2d3c32-2181-44a0-96c6-340389b5ac46"
}

# equb_members

###
GET http://127.0.0.1:8000/all_equb_members/9c2d3c32-2181-44a0-96c6-340389b5ac46/
Authorization: Token 326323294ec879e27e35ed6d28387ff815eaff2f
Content-Type: application/json


# preview_equb_winner

###
GET http://127.0.0.1:8000/preview_equb_winner/9c2d3c32-2181-44a0-96c6-340389b5ac46/
Authorization: Token 326323294ec879e27e35ed6d28387ff815eaff2f
Content-Type: application/json


# confirm_and_save_winner

###
POST http://127.0.0.1:8000/confirm_and_save_winner/
Authorization: Token 326323294ec879e27e35ed6d28387ff815eaff2f
Content-Type: application/json


{
      "user": "1",
      "equb": "9c2d3c32-2181-44a0-96c6-340389b5ac46"
}

# "admin_equb_report"

###
GET http://127.0.0.1:8000/admin_equb_report/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json

# equb_detailed_report

###
GET http://127.0.0.1:8000/equb_detailed_report/9c2d3c32-2181-44a0-96c6-340389b5ac46/
Authorization: Token 5b3955a585617d369f2e058e76551704a8b08f0f
Content-Type: application/json


# list_user_payment_history

###
GET http://127.0.0.1:8000/list_user_payment_history/1/
Authorization: Token 326323294ec879e27e35ed6d28387ff815eaff2f
Content-Type: application/json
