# Generated by Django 5.2 on 2026-02-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equbApp", "0002_payment_approved_at_payment_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
