# Generated by Django 5.2 on 2026-04-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equbApp", "0003_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="equb",
            name="payout_account_holder_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="equb",
            name="payout_account_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="equb",
            name="payout_bank_code",
            field=models.CharField(
                blank=True,
                help_text="Bank or wallet code from predefined list (e.g. CBE, TBR)",
                max_length=10,
                null=True,
            ),
        ),
    ]
