# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equbApp", "0006_equb_multiple_payout_bank_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="chapa_checkout_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
