# Generated by Django 5.2 on 2026-05-24 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equbApp", "0007_payment_add_chapa_checkout_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "latest_version",
                    models.CharField(
                        default="1.0.0",
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Must be valid semver MAJOR.MINOR.PATCH (e.g. 1.2.3).",
                                regex="^\\d+\\.\\d+\\.\\d+$",
                            )
                        ],
                    ),
                ),
                ("force_update", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App Config",
                "verbose_name_plural": "App Config",
            },
        ),
    ]
