# Generated by Django 5.2 on 2026-09-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equbApp", "0008_appconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
