# Generated by Django 5.2 on 2026-09-27 19:10

import equbApp.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equbApp", "0009_notification_is_pinned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="receipt_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=equbApp.uploads.receipt_upload_path
            ),
        ),
    ]
